### ISSUE TITLE
Feature: Add thumbnails for preview on FB for sharing

### ISSUE THREAD

**Issue by 1000miles** [cssconf/CSSclasses#17]
Dear CSSClasses team,
I wanted to share your website link http://cssclasses.cssconf.eu/ on Facebook but I saw that until now there is no thumbnail pic for preview. As we all know people love to see images on social media before they click on a link, I wanted to suggest this. :)

Cheers,
Thuy

![fb-screenshot](https://cloud.githubusercontent.com/assets/4077916/11090551/061cf744-8873-11e5-9900-328e3d6db0d8.png)

**Comment by lukaszklis** [comment]
Fixed in 80ef769c63afd1088a9a9ebf46f594dff5b4647f
