### ISSUE TITLE
Enhance the header on the subpages

### ISSUE THREAD

**Issue by radibit** [cssconf/CSSclasses#5]
My suggestion is to replace the hero image on the subpages with a smaller top bar containing only the logo e.g. centre aligned logo with a transparent background. 

With this approach we can improve the UX of presenting the people immediately with the context of the selected page :-)

**Comment by verpixelt** [comment]
Sure, open a feature branch and play around with it. I can't promise that we will include it right away, but feel free to go ahead and send us a proposal.
